# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = """$character"""

# right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

# Disable the package module, hiding it from the prompt completely
[aws]
disabled = true
